CC=gcc

all: Leaf_Counter Aggregate_Votes Vote_Counter

Leaf_Counter:
	$(CC) -o Leaf_Counter Leaf_Counter.c 
	
Aggregate_Votes:
	$(CC) -o Aggregate_Votes Aggregate_Votes.c
	
Vote_Counter: 
	$(CC) -o Vote_Counter Vote_Counter.c

clean:
	rm Leaf_Counter Aggregate_Votes Vote_Counter